name: phenomenal_dev
channels:
  - openalea3/label/dev
  - openalea3/label/rc
  - openalea3
  - conda-forge
dependencies:
  - python
  - pip
  - cxx-compiler
  - opencv
  - openalea.phenotyping_data
  - pip:
      - -e ..[doc,test,viz]
